title: A Semester in Digital Humanities
description: Vasu Gupta's semester portfolio showcasing projects and reflections in the field of digital humanities.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
